# Integrated Workflow Configuration
# Configuration for spec-to-production workflow

# Quality Gate Thresholds
quality_gates:
  # Testing gates
  test_coverage:
    dev_threshold: 50.0 # Minimum coverage for development
    staging_threshold: 70.0 # Minimum coverage for staging promotion
    production_threshold: 80.0 # Minimum coverage for production promotion

  test_pass_rate:
    required: 100.0 # All tests must pass

  # Code quality gates
  linting:
    max_issues: 0 # No linting issues allowed
    auto_fix: true # Automatically fix issues where possible

  type_checking:
    max_errors: 0 # No type errors allowed

  security:
    max_critical: 0 # No critical security issues
    max_high: 0 # No high security issues
    max_medium: 5 # Up to 5 medium security issues allowed

  # Performance gates (placeholder)
  performance:
    max_response_time_ms: 5000
    max_memory_mb: 512

# Error Recovery Configuration
error_recovery:
  # Retry configuration by stage
  testing:
    max_retries: 3
    base_delay: 1.0
    exponential_base: 2.0
    max_delay: 10.0
    jitter: true

  staging_deployment:
    max_retries: 5
    base_delay: 2.0
    exponential_base: 2.0
    max_delay: 30.0
    jitter: true

  production_deployment:
    max_retries: 3
    base_delay: 5.0
    exponential_base: 1.5
    max_delay: 60.0
    jitter: true

  # Circuit breaker configuration
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60.0
    half_open_max_calls: 1

# Observability Configuration
observability:
  # Metrics collection
  metrics:
    enabled: true
    metrics_dir: ".metrics"
    retention_days: 30

  # Dashboard generation
  dashboard:
    enabled: true
    auto_generate: true
    output_dir: "workflow_dashboards"

  # Metrics to track
  track_metrics:
    - stage_execution_time
    - quality_gate_results
    - retry_count
    - error_types
    - success_rate

# AI Context Management Configuration
context_management:
  # Session configuration
  session:
    enabled: true
    max_tokens: 8000
    auto_save: true

  # Importance scoring
  importance:
    architectural_decisions: 1.0
    requirements: 1.0
    production_status: 1.0
    implementation_completion: 0.9
    test_results: 0.9
    deployment_status: 0.9
    refactoring_decisions: 0.7
    progress_updates: 0.5

  # Pruning strategy
  pruning:
    preserve_system_messages: true
    preserve_high_importance: true # importance >= 0.8
    preserve_recent_count: 5

# Component Maturity Workflow
maturity_workflow:
  # Development stage
  development:
    required_gates:
      - test_pass_rate
      - linting
    optional_gates:
      - test_coverage
      - type_checking

  # Staging stage
  staging:
    required_gates:
      - test_coverage # >= 70%
      - test_pass_rate
      - linting
      - type_checking
      - security
    optional_gates:
      - performance

  # Production stage
  production:
    required_gates:
      - test_coverage # >= 80% integration tests
      - test_pass_rate
      - linting
      - type_checking
      - security
      - performance
    additional_requirements:
      - staging_uptime_days: 7
      - staging_uptime_percentage: 99.5
      - security_review_complete: true
      - documentation_complete: true
      - monitoring_configured: true
      - rollback_tested: true

# Workflow Stages
stages:
  specification:
    enabled: true
    timeout_seconds: 60

  implementation:
    enabled: false # Not yet implemented
    timeout_seconds: 3600

  testing:
    enabled: true
    timeout_seconds: 600
    parallel_execution: false

  openhands_test_generation:
    enabled: false # Disabled by default - enable with --enable-openhands
    timeout_seconds: 300
    coverage_threshold: 80
    use_docker: true # Use Docker runtime for full tool access

  refactoring:
    enabled: true
    timeout_seconds: 300
    auto_fix_linting: true

  staging_deployment:
    enabled: true
    timeout_seconds: 600
    rollback_on_failure: true

  production_deployment:
    enabled: true
    timeout_seconds: 900
    rollback_on_failure: true
    require_manual_approval: false # Set to true for production safety

# Notification Configuration (placeholder)
notifications:
  enabled: false
  channels:
    - email
    - slack
  events:
    - workflow_complete
    - workflow_failed
    - stage_failed
    - quality_gate_failed

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "workflow.log"
  console: true
