# TTA Specification Quality Standards Configuration
# This file defines quality standards, metrics, and thresholds for TTA specifications

quality_standards:
  # Overall quality score thresholds
  score_thresholds:
    excellent: 90  # Grade A
    good: 80       # Grade B  
    acceptable: 70 # Grade C
    needs_improvement: 60  # Grade D
    failing: 0     # Grade F
  
  # Component scoring weights
  scoring_weights:
    completeness: 0.4   # 40% - Required sections and content depth
    alignment: 0.3      # 30% - Implementation references and status accuracy
    freshness: 0.2      # 20% - Last update and review schedule
    validation: 0.1     # 10% - Test coverage and acceptance criteria
  
  # Completeness requirements
  completeness:
    required_sections:
      - "Overview"
      - "Implementation Status"
      - "Requirements" 
      - "Technical Design"
      - "Testing Strategy"
      - "Validation Checklist"
    
    content_depth_indicators:
      - code_blocks: 2        # Minimum code examples
      - acceptance_criteria: 3 # Minimum WHEN/THEN statements
      - implementation_refs: 1 # Minimum file references
      - api_endpoints: 0      # Minimum API references (if applicable)
      - test_references: 1    # Minimum test file references
    
    minimum_word_count: 500   # Minimum words for substantial content
  
  # Alignment requirements
  alignment:
    required_fields:
      - status_indicator      # Must have valid status (✅🚧❌📋)
      - implementation_ref    # Must reference actual files
      - version_number       # Must have semantic version
      - owner_assignment     # Must have assigned owner
    
    valid_status_indicators:
      - "✅ OPERATIONAL"
      - "🚧 IN_PROGRESS"
      - "❌ OUTDATED"
      - "📋 PLANNED"
    
    placeholder_penalties:
      - "TBD": 5             # Points deducted per TBD
      - "TODO": 5            # Points deducted per TODO
      - "{PLACEHOLDER}": 10  # Points deducted per template placeholder
  
  # Freshness requirements
  freshness:
    staleness_thresholds:
      critical: 30    # Days - Critical specs must be updated monthly
      high: 90        # Days - High priority specs quarterly
      medium: 180     # Days - Medium priority specs bi-annually
      low: 365        # Days - Low priority specs annually
    
    review_schedule_required: true
    last_updated_required: true
  
  # Validation requirements
  validation:
    minimum_checklist_items: 5
    required_test_patterns:
      - "tests/"
      - "test_"
      - "pytest"
      - "unittest"
    
    acceptance_criteria_format: "WHEN .+ THEN"
    minimum_acceptance_criteria: 3

# Category-specific standards
category_standards:
  therapeutic-systems:
    # Higher standards for therapeutic systems due to safety requirements
    score_thresholds:
      excellent: 95
      good: 85
      acceptable: 75
      needs_improvement: 65
    
    additional_requirements:
      - safety_validation_refs: true
      - crisis_handling_docs: true
      - therapeutic_compliance: true
      - performance_benchmarks: true
    
    required_sections:
      - "Therapeutic Safety Considerations"
      - "Crisis Intervention Protocols"
      - "Performance Requirements"
      - "Clinical Validation"
  
  web-interfaces:
    additional_requirements:
      - accessibility_compliance: "WCAG 2.1 AA"
      - authentication_docs: true
      - ui_component_refs: true
      - responsive_design_notes: true
    
    required_sections:
      - "User Experience Design"
      - "Accessibility Requirements"
      - "Authentication Integration"
  
  infrastructure:
    additional_requirements:
      - deployment_instructions: true
      - monitoring_setup: true
      - backup_procedures: true
      - security_configuration: true
    
    required_sections:
      - "Deployment Configuration"
      - "Monitoring and Alerting"
      - "Security Requirements"
      - "Backup and Recovery"
  
  ai-orchestration:
    additional_requirements:
      - agent_interaction_diagrams: true
      - performance_metrics: true
      - resource_management: true
      - error_handling_strategies: true
    
    required_sections:
      - "Agent Architecture"
      - "Performance Optimization"
      - "Resource Management"
      - "Error Recovery"
  
  shared-components:
    additional_requirements:
      - api_documentation: true
      - usage_examples: true
      - integration_guides: true
      - version_compatibility: true
    
    required_sections:
      - "API Documentation"
      - "Usage Examples"
      - "Integration Guide"
      - "Version Compatibility"

# Automated quality checks
automated_checks:
  # Pre-commit validation rules
  pre_commit:
    enabled: true
    fail_on_score_below: 60
    critical_system_score_threshold: 75
    
    checks:
      - template_compliance
      - required_sections
      - status_indicator_validity
      - implementation_references
      - metadata_completeness
  
  # CI/CD pipeline checks
  ci_pipeline:
    enabled: true
    generate_quality_reports: true
    fail_build_on_critical_issues: true
    
    quality_gates:
      - minimum_average_score: 70
      - maximum_failing_specs: 3
      - critical_systems_minimum_score: 80
  
  # Scheduled quality audits
  scheduled_audits:
    enabled: true
    frequency: "weekly"
    
    audit_types:
      - completeness_check
      - alignment_verification
      - freshness_review
      - broken_link_detection

# Reporting configuration
reporting:
  # Quality dashboard settings
  dashboard:
    enabled: true
    update_frequency: "daily"
    
    metrics:
      - overall_quality_trend
      - category_performance
      - specification_health
      - improvement_recommendations
  
  # Notification settings
  notifications:
    enabled: true
    
    triggers:
      - quality_score_drop: 10  # Points
      - specification_stale: 90  # Days
      - critical_system_issues: true
      - missing_specifications: true
    
    channels:
      - email: "dev-team@tta.example.com"
      - slack: "#tta-specifications"
      - github_issues: true

# Quality improvement workflows
improvement_workflows:
  # Specification review process
  review_process:
    enabled: true
    
    triggers:
      - score_below_threshold: 70
      - staleness_exceeded: true
      - implementation_changes: true
    
    workflow_steps:
      - assign_reviewer
      - schedule_review_meeting
      - update_specification
      - validate_improvements
      - close_review_cycle
  
  # Automated improvement suggestions
  auto_suggestions:
    enabled: true
    
    suggestion_types:
      - missing_sections
      - outdated_references
      - incomplete_checklists
      - stale_content_updates
      - alignment_improvements

# Integration settings
integrations:
  # GitHub integration
  github:
    enabled: true
    create_issues_for_quality_problems: true
    label_specifications_by_quality: true
    
    quality_labels:
      - "spec-quality-excellent"
      - "spec-quality-good"
      - "spec-quality-needs-improvement"
      - "spec-quality-failing"
  
  # Development tools integration
  development_tools:
    vscode_extension: true
    pre_commit_hooks: true
    ci_cd_integration: true
    
    editor_features:
      - real_time_quality_scoring
      - inline_improvement_suggestions
      - template_auto_completion
      - reference_validation

# Maintenance settings
maintenance:
  # Cleanup policies
  cleanup:
    archive_outdated_specs: false  # Keep for historical reference
    remove_placeholder_content: true
    consolidate_duplicate_specs: true
  
  # Update policies
  updates:
    auto_update_timestamps: true
    version_bump_on_changes: true
    maintain_change_history: true
  
  # Backup and versioning
  versioning:
    semantic_versioning: true
    maintain_version_history: true
    backup_before_major_changes: true
