# OpenHands Configuration for OpenRouter Integration
# This config uses OpenRouter with free models for cost optimization

[llm]
model = "meta-llama/llama-3.1-8b-instruct:free"
api_key = "${OPENROUTER_API_KEY}"
base_url = "https://openrouter.ai/api/v1"
temperature = 0.7
max_tokens = 2048

[agent]
name = "CodeActAgent"
memory_enabled = true

[core]
workspace_base = "/tmp/openhands_test"
cache_dir = "/tmp/openhands_cache"

