# Pre-commit configuration for TTA project
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=88"]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=88"]

  # Linting with ruff (replaces flake8, pylint, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          [types-requests, types-PyYAML, types-redis, types-setuptools]
        args:
          [--ignore-missing-imports, --no-strict-optional, --show-error-codes]
        exclude: ^(tests/|docs/|scripts/|examples/|tta\.prototype/|tta\.dev/|tta\.prod/)

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-r", "src/", "-f", "json", "-o", "bandit-report.json"]
        exclude: ^(tests/|docs/|scripts/|examples/)

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [optional-scope]

  # Python docstring formatting (warning only for now)
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          [
            "--convention=google",
            "--add-ignore=D100,D101,D102,D103,D104,D105,D106,D107,D212",
          ]
        exclude: ^(tests/|docs/|scripts/|examples/|tta\.prototype/|tta\.dev/|tta\.prod/)

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^(.github/|docker-compose|\.codecarbon/|\.kiro/)

# Configuration for specific tools
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false

# Exclude patterns
exclude: |
  (?x)^(
    \.venv/|
    venv/|
    __pycache__/|
    \.git/|
    \.mypy_cache/|
    \.pytest_cache/|
    \.ruff_cache/|
    build/|
    dist/|
    \.eggs/|
    \.tox/|
    htmlcov/|
    coverage\.xml|
    \.coverage|
    bandit-report\.json|
    logs/|
    data/|
    \.env|
    \.env\..*|
    uv\.lock|
    .*\.backup\.\d+|
    tta/prod/src/utils/neo4j_utils\.py|
    validate_live_databases\.py|
    templates/.*\.json|
    .*\.k8s/.*\.yaml
  )$
