# Pre-commit configuration for TTA project
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]

  # Ruff: Combined linting, formatting, and import sorting (replaces Black, isort, flake8, pylint)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      # Run linter with auto-fix
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      # Run formatter
      - id: ruff-format
        types_or: [python, pyi]

  # Type checking - MOVED TO CI/CD ONLY for performance
  # MyPy is too slow for pre-commit hooks in solo developer workflow
  # Run manually with: uv run mypy src/
  # Or in CI/CD pipeline for comprehensive type checking

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-r", "src/", "-f", "json", "-o", "bandit-report.json"]
        exclude: ^(tests/|docs/|scripts/|examples/)

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: |
          (?x)^(
            \.secrets\.baseline|
            uv\.lock|
            package-lock\.json|
            .*\.ipynb|
            tests/.*
          )$

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [optional-scope]

  # Python docstring formatting (warning only for now)
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          [
            "--convention=google",
            "--add-ignore=D100,D101,D102,D103,D104,D105,D106,D107,D212",
          ]
        exclude: ^(tests/|docs/|scripts/|examples/|tta\.prototype/|tta\.dev/|tta\.prod/)

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^(.github/|docker-compose|\.codecarbon/|\.kiro/)

  # Local custom hooks
  - repo: local
    hooks:
      # Custom hook: Check pytest-asyncio fixture decorators
      - id: check-pytest-asyncio-fixtures
        name: Check pytest-asyncio fixture decorators
        entry: python scripts/pre-commit/check-pytest-asyncio-fixtures.py
        language: system
        types: [python]
        files: ^tests/.*\.py$
        pass_filenames: true

# Configuration for specific tools
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false

# Exclude patterns
exclude: |
  (?x)^(
    \.venv/|
    venv/|
    __pycache__/|
    \.git/|
    \.mypy_cache/|
    \.pytest_cache/|
    \.ruff_cache/|
    build/|
    dist/|
    \.eggs/|
    \.tox/|
    htmlcov/|
    coverage\.xml|
    \.coverage|
    bandit-report\.json|
    logs/|
    data/|
    \.env|
    \.env\..*|
    uv\.lock|
    .*\.backup\.\d+|
    tta/prod/src/utils/neo4j_utils\.py|
    validate_live_databases\.py|
    templates/.*\.json|
    .*\.k8s/.*\.yaml
  )$
