# Exclude files and directories
ignore-paths:
  - .venv
  - .uv_cache
  - venv
  - tests
  - docs
  - scripts
  - obsolete
  - artifacts
  - node_modules
  - __pycache__

# Disable tools already covered by ruff
tools:
  pycodestyle:
    enabled: false
  pydocstyle:
    enabled: false
  pyflakes:
    enabled: false
  mccabe:
    enabled: false # covered by ruff's C901
  isort:
    enabled: false # covered by ruff's I
  bandit:
    enabled: false # covered by ruff's S
