version: '3.8'
services:
  neo4j:
    image: neo4j:5-community
    container_name: ${CONTAINER_PREFIX:-tta-dev}-neo4j
    ports:
    - 7474:7474
    - 7687:7687
    environment:
    - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/tta_dev_password_2024}
    - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
    - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
    - NEO4J_dbms_memory_heap_initial__size=1G
    - NEO4J_dbms_memory_heap_max__size=2G
    - NEO4J_dbms_memory_pagecache_size=512m
    - NEO4J_dbms_logs_debug_level=${LOG_LEVEL:-INFO}
    volumes:
    - neo4j_dev_data:/data
    - neo4j_dev_logs:/logs
    - neo4j_dev_import:/var/lib/neo4j/import
    - neo4j_dev_plugins:/plugins
    healthcheck:
      test:
      - CMD-SHELL
      - wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_PREFIX:-tta-dev}-redis
    ports:
    - 6379:6379
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
      ${REDIS_AUTH:+--requirepass $REDIS_PASSWORD}
    volumes:
    - redis_dev_data:/data
    - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tta-redis-commander-dev
    ports:
    - 8081:8081
    environment:
    - REDIS_HOSTS=local:redis:6379
    depends_on:
    - redis
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
  neo4j-browser:
    image: neo4j/neo4j-browser:latest
    container_name: tta-neo4j-browser
    ports:
    - 8080:8080
    environment:
    - NEO4J_URI=bolt://neo4j:7687
    depends_on:
    - neo4j
    profiles:
    - tools
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
  grafana:
    image: grafana/grafana:latest
    container_name: tta-grafana-dev
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
    - grafana_dev_data:/var/lib/grafana
    - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ./monitoring/grafana/datasources/prometheus-dev.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
    - ./monitoring/grafana/datasources/additional-datasources.yml:/etc/grafana/provisioning/datasources/additional.yml:ro
    profiles:
    - monitoring
    depends_on:
    - prometheus
    - loki
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
  prometheus:
    image: prom/prometheus:latest
    container_name: tta-prometheus-dev
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
    - ./monitoring/rules:/etc/prometheus/rules:ro
    - prometheus_dev_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --web.enable-lifecycle
    - --storage.tsdb.retention.time=7d
    profiles:
    - monitoring
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
  node-exporter:
    image: prom/node-exporter:latest
    container_name: tta-node-exporter-dev
    ports:
    - 9100:9100
    command:
    - --path.procfs=/host/proc
    - --path.rootfs=/rootfs
    - --path.sysfs=/host/sys
    - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    profiles:
    - monitoring
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
  loki:
    image: grafana/loki:2.9.0
    container_name: tta-loki-dev
    ports:
    - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
    - loki_dev_data:/loki
    profiles:
    - monitoring
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
  promtail:
    image: grafana/promtail:2.9.0
    container_name: tta-promtail-dev
    volumes:
    - /var/log:/var/log:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - ./monitoring/promtail/promtail.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    profiles:
    - monitoring
    depends_on:
    - loki
    networks:
    - tta-dev-network
    security_opt:
    - no-new-privileges:true
volumes:
  neo4j_dev_data:
    name: tta_neo4j_dev_data
  neo4j_dev_logs:
    name: tta_neo4j_dev_logs
  neo4j_dev_import:
    name: tta_neo4j_dev_import
  neo4j_dev_plugins:
    name: tta_neo4j_dev_plugins
  redis_dev_data:
    name: tta_redis_dev_data
  grafana_dev_data:
    name: tta_grafana_dev_data
  prometheus_dev_data:
    name: tta_prometheus_dev_data
  loki_dev_data:
    name: tta_loki_dev_data
networks:
  tta-dev-network:
    name: tta-dev-network
    driver: bridge
