version: '3.8'
services:
  neo4j:
    image: neo4j:5-community
    container_name: ${CONTAINER_PREFIX:-tta-test}-neo4j
    ports:
    - 7474:7474
    - 7687:7687
    environment:
    - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/tta_test_password_2024}
    - NEO4J_PLUGINS=["apoc"]
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    - NEO4J_dbms_security_procedures_allowlist=apoc.*
    - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
    - NEO4J_dbms_memory_heap_initial__size=512m
    - NEO4J_dbms_memory_heap_max__size=1G
    - NEO4J_dbms_memory_pagecache_size=256m
    - NEO4J_dbms_logs_debug_level=${LOG_LEVEL:-INFO}
    volumes:
    - neo4j_test_data:/data
    - neo4j_test_logs:/logs
    healthcheck:
      test:
      - CMD-SHELL
      - wget --no-verbose --tries=1 --spider http://localhost:7474/db/data/ || exit
        1
      interval: 15s
      timeout: 15s
      retries: ${MAX_HEALTH_RETRIES:-8}
      start_period: 60s
    restart: unless-stopped
    networks:
    - tta-test-network
    security_opt:
    - no-new-privileges:true
  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_PREFIX:-tta-test}-redis
    ports:
    - 6379:6379
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
      ${REDIS_AUTH:+--requirepass $REDIS_PASSWORD}
    volumes:
    - redis_test_data:/data
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
    - tta-test-network
    security_opt:
    - no-new-privileges:true
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tta-redis-commander
    ports:
    - 8081:8081
    environment:
    - REDIS_HOSTS=local:redis:6379
    depends_on:
    - redis
    profiles:
    - tools
    networks:
    - tta-test-network
    security_opt:
    - no-new-privileges:true
volumes:
  neo4j_test_data:
    name: tta_neo4j_test_data
  neo4j_test_logs:
    name: tta_neo4j_test_logs
  redis_test_data:
    name: tta_redis_test_data
networks:
  tta-test-network:
    name: tta-test-network
    driver: bridge
