
services:
  neo4j-staging:
    image: neo4j:5.15-community
    container_name: tta-neo4j-staging
    ports:
      - "7690:7687"  # Bolt protocol (mapped to unique external port, avoiding 7689 conflict)
      - "7476:7474"  # HTTP (mapped to unique external port, avoiding 7475 conflict)
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-staging_password_change_me}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_default__database=tta-staging
    volumes:
      - neo4j_staging_data:/data
      - neo4j_staging_logs:/logs
      - neo4j_staging_import:/var/lib/neo4j/import
      - neo4j_staging_plugins:/plugins
    networks:
      - tta-staging-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 6G
        reservations:
          cpus: '1.0'
          memory: 3G
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD:-staging_password_change_me}", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

volumes:
  neo4j_staging_data:
    driver: local
  neo4j_staging_logs:
    driver: local
  neo4j_staging_import:
    driver: local
  neo4j_staging_plugins:
    driver: local

networks:
  tta-staging-network:
    driver: bridge
