services:
  redis:
    image: redis:7.2.4-alpine3.19
    container_name: tta-redis
    ports:
    - 6379:6379
    volumes:
    - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    security_opt:
    - no-new-privileges:true
volumes:
  redis-data: null
