site_name: TTA - Therapeutic Text Adventure
site_description: Documentation for the TTA monorepo and reusable packages
site_author: TTA Development Team
site_url: https://theinterneti.github.io/TTA/

repo_name: theinterneti/TTA
repo_url: https://github.com/theinterneti/TTA
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theinterneti/TTA
  version:
    provider: mike
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by
            <a href="https://github.com/theinterneti/TTA/issues/new" target="_blank" rel="noopener">opening an issue</a>.

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mermaid2:
      version: 10.6.1
  - mkdocstrings:
      handlers:
        python:
          paths:
            [
              packages/tta-ai-framework/src,
              packages/tta-narrative-engine/src,
              src,
            ]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            group_by_category: true
            show_category_heading: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Configuration: getting-started/configuration.md

  - Packages:
      - Overview: packages/overview.md
      - TTA AI Framework:
          - Introduction: packages/tta-ai-framework/index.md
          - Orchestration: packages/tta-ai-framework/orchestration.md
          - Model Management: packages/tta-ai-framework/models.md
          - Prompt Registry: packages/tta-ai-framework/prompts.md
          - API Reference: packages/tta-ai-framework/api.md
      - TTA Narrative Engine:
          - Introduction: packages/tta-narrative-engine/index.md
          - Scene Generation: packages/tta-narrative-engine/generation.md
          - Narrative Orchestration: packages/tta-narrative-engine/orchestration.md
          - Coherence Validation: packages/tta-narrative-engine/coherence.md
          - API Reference: packages/tta-narrative-engine/api.md

  - TTA Application:
      - Overview: application/overview.md
      - Architecture: application/architecture.md
      - Player Experience: application/player-experience.md
      - Therapeutic Systems: application/therapeutic-systems.md
      - API Gateway: application/api-gateway.md

  - Development:
      - Component Maturity: development/component-maturity.md
      - Testing Strategy: development/testing.md
      - Contributing: development/contributing.md
      - Code Style: development/code-style.md
      - CI/CD: development/cicd.md

  - Architecture:
      - Overview: architecture/overview.md
      - Dependency Graph: architecture/dependency-graph.md
      - Database Design: architecture/database.md
      - Agent Orchestration: architecture/agent-orchestration.md
      - Agentic Primitives: architecture/agentic-primitives-quick-reference.md

  - Deployment:
      - Overview: deployment/overview.md
      - Development: deployment/development.md
      - Staging: deployment/staging.md
      - Production: deployment/production.md

  - API Reference:
      - TTA AI Framework: api/tta-ai-framework.md
      - TTA Narrative Engine: api/tta-narrative-engine.md
      - TTA Application: api/tta-application.md

copyright: Copyright &copy; 2024 TTA Development Team
