version: "3.8"

services:
  # Neo4j Database Service
  neo4j:
    image: neo4j:5.15-community
    container_name: tta-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/TTA_Neo4j_2024!

      # Memory Configuration
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1G
      NEO4J_server_memory_pagecache_size: 512m

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./database/neo4j/init:/docker-entrypoint-initdb.d
    networks:
      - tta-network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p TTA_Neo4j_2024! 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Redis Cache Service
  redis:
    image: redis:7.2-alpine
    container_name: tta-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass TTA_Redis_2024!
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --tcp-keepalive 300
      --timeout 0
      --tcp-backlog 511
      --databases 16
    volumes:
      - redis_data:/data
      - ./database/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - tta-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "TTA_Redis_2024!", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  # Neo4j Volumes
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

  # Redis Volumes
  redis_data:
    driver: local

networks:
  tta-network:
    driver: bridge
