apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
  namespace: tta-player-experience
  labels:
    app.kubernetes.io/name: tta-player-experience
    app.kubernetes.io/component: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tta-player-experience
      app.kubernetes.io/component: neo4j
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tta-player-experience
        app.kubernetes.io/component: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.15-community
        ports:
        - containerPort: 7687
        - containerPort: 7474
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: player-experience-secrets
              key: API_NEO4J_PASSWORD
        - name: NEO4J_PLUGINS
          value: '["apoc"]'
        - name: NEO4J_dbms_security_procedures_unrestricted
          value: "apoc.*"
        - name: NEO4J_dbms_memory_heap_initial__size
          value: "512m"
        - name: NEO4J_dbms_memory_heap_max__size
          value: "2G"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
        livenessProbe:
          exec:
            command:
            - cypher-shell
            - -u
            - neo4j
            - -p
            - password
            - "RETURN 1"
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - cypher-shell
            - -u
            - neo4j
            - -p
            - password
            - "RETURN 1"
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data-pvc
      - name: neo4j-logs
        persistentVolumeClaim:
          claimName: neo4j-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: tta-player-experience
  labels:
    app.kubernetes.io/name: tta-player-experience
    app.kubernetes.io/component: neo4j
spec:
  selector:
    app.kubernetes.io/name: tta-player-experience
    app.kubernetes.io/component: neo4j
  ports:
  - name: bolt
    port: 7687
    targetPort: 7687
  - name: http
    port: 7474
    targetPort: 7474
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: tta-player-experience
  labels:
    app.kubernetes.io/name: tta-player-experience
    app.kubernetes.io/component: neo4j
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-pvc
  namespace: tta-player-experience
  labels:
    app.kubernetes.io/name: tta-player-experience
    app.kubernetes.io/component: neo4j
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi