global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alerts@tta-system.local"
  smtp_auth_username: "alerts@tta-system.local"
  smtp_auth_password: "password"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"
  routes:
    - match:
        severity: critical
      receiver: "critical-alerts"
    - match:
        severity: warning
      receiver: "warning-alerts"

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://localhost:8000/api/v1/alerts/webhook"
        send_resolved: true

  - name: "critical-alerts"
    webhook_configs:
      - url: "http://localhost:8000/api/v1/alerts/webhook"
        send_resolved: true
    email_configs:
      - to: "admin@tta-system.local"
        subject: "TTA Critical Alert: {{ .GroupLabels.alertname }}"
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: "warning-alerts"
    webhook_configs:
      - url: "http://localhost:8000/api/v1/alerts/webhook"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
