services:
  prometheus:
    image: prom/prometheus:v2.48.1:latest
    container_name: tta-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --storage.tsdb.retention.time=200h
      - --web.enable-lifecycle
      - --web.enable-admin-api
    networks:
      - tta-monitoring
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  grafana:
    image: grafana/grafana:10.2.3:10.2.3
    container_name: tta-grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - tta-monitoring
    restart: unless-stopped
    depends_on:
      - prometheus
    security_opt:
      - no-new-privileges:true
  alertmanager:
    image: prom/alertmanager:latest
    container_name: tta-alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.external-url=http://localhost:9093
    networks:
      - tta-monitoring
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  node-exporter:
    image: prom/node-exporter:latest
    container_name: tta-node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    networks:
      - tta-monitoring
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
  redis:
    image: redis:7.2.4-alpine3.19
    container_name: tta-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - tta-monitoring
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  postgres:
    image: postgres:15-alpine
    container_name: tta-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tta
      - POSTGRES_USER=tta
      - POSTGRES_PASSWORD=tta_password
    networks:
      - tta-monitoring
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
volumes:
  prometheus_data: null
  grafana_data: null
  alertmanager_data: null
  redis_data: null
  postgres_data: null
networks:
  tta-monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
