# TTA Enhanced Extended Session Quality Evaluation Framework
# Phase 2: Full Integration Validation Configuration

# Database Configuration
database:
  # Redis Configuration (Test Database)
  redis_url: "redis://localhost:6379/1" # Use DB 1 for testing to avoid conflicts
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 1
  redis_password: ""

  # Neo4j Configuration (Integration Test User)
  neo4j_uri: "bolt://localhost:7687"
  neo4j_user: "tta_integration"
  neo4j_password: "tta_integration_password_2024"
  neo4j_database: "neo4j"

# Testing Configuration
testing:
  # Session Testing
  session_count: 10
  ultra_extended_turns: 200
  concurrent_users: 5
  test_timeout_seconds: 300

  # Performance Testing
  max_memory_usage_mb: 512
  max_response_time_seconds: 5.0

  # Stress Testing
  adversarial_scenarios: 5
  error_injection_rate: 0.1

# Validation Configuration
validation:
  # Database Validation
  verify_schema_creation: true
  verify_cache_consistency: true
  verify_data_persistence: true
  verify_constraint_enforcement: true

  # Cleanup Configuration
  cleanup_test_data: true
  preserve_schema: true

  # Reporting Configuration
  generate_detailed_report: true
  include_performance_metrics: true
  include_database_statistics: true

# Integration Test Scenarios
scenarios:
  # Ultra-Extended Session Scenarios
  ultra_extended:
    - name: "Epic Fantasy Adventure (200+ turns)"
      turns: 200
      genre: "fantasy"
      complexity: "high"
      therapeutic_focus: "emotional_regulation"

    - name: "Modern Therapy Session (250+ turns)"
      turns: 250
      genre: "contemporary"
      complexity: "medium"
      therapeutic_focus: "anxiety_management"

  # Multi-User Concurrent Scenarios
  concurrent:
    - name: "Shared World Adventure"
      users: 5
      shared_world: true
      conflict_resolution: "collaborative"

    - name: "Individual Therapy Sessions"
      users: 3
      shared_world: false
      conflict_resolution: "isolated"

  # Adversarial Testing Scenarios
  adversarial:
    - name: "Rapid Fire Interactions"
      interaction_rate: "high"
      error_injection: true

    - name: "Memory Stress Test"
      memory_pressure: "high"
      context_overflow: true

# Expected Results (for validation)
expected_results:
  # Database Schema
  neo4j_constraints_min: 5
  neo4j_indexes_min: 8

  # Performance Benchmarks
  session_creation_max_time_ms: 100
  session_retrieval_max_time_ms: 50
  ultra_extended_session_max_time_minutes: 10

  # Reliability Benchmarks
  data_persistence_success_rate: 100.0
  cache_consistency_success_rate: 100.0
  concurrent_access_success_rate: 95.0

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "testing/logs/integration_validation.log"
  console: true
