name: 🔒 Security Vulnerability
description: Report a security vulnerability (use private reporting for critical issues)
title: "[SECURITY]: "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Security Notice

        **For critical security vulnerabilities, please use [GitHub's private vulnerability reporting](https://github.com/theinterneti/TTA/security/advisories/new) instead of creating a public issue.**

        This template is for:
        - Non-critical security concerns
        - Security improvement suggestions
        - Security-related questions

        If you're unsure whether your finding is critical, err on the side of caution and use private reporting.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Critical - Immediate action required
        - High - Significant security risk
        - Medium - Moderate security concern
        - Low - Minor security improvement
        - Informational - Security best practice suggestion
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Authentication / Authorization
        - Data Exposure / Privacy
        - Injection (SQL, XSS, etc.)
        - Cryptography
        - API Security
        - Dependency Vulnerability
        - Configuration Issue
        - Access Control
        - Session Management
        - Input Validation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security vulnerability or concern
      placeholder: |
        Provide a clear description of the security issue, but avoid including exploit details in public issues.
    validations:
      required: true

  - type: dropdown
    id: affected-components
    attributes:
      label: Affected Components
      description: Which components are affected?
      multiple: true
      options:
        - API / Backend
        - Frontend / UI
        - Authentication System
        - Database Layer
        - LangGraph / AI Processing
        - Docker / Deployment
        - CI/CD Pipeline
        - Documentation
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially do with this vulnerability?
      placeholder: |
        Example: An attacker could potentially access user data without authentication
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this security issue?
      placeholder: |
        Example: v1.0.0 through v1.2.3
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: How can this security issue be reproduced? (Avoid detailed exploit instructions in public issues)
      placeholder: |
        1. Navigate to '...'
        2. Attempt to '...'
        3. Observe security issue
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to fix or mitigate this issue?
      placeholder: |
        Example: Implement proper input validation and sanitization
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Include any relevant security advisories, CVEs, or documentation
      placeholder: |
        - CVE-2024-XXXXX
        - OWASP Top 10: A01:2021
        - Related security advisory: https://...
    validations:
      required: false

  - type: dropdown
    id: disclosure
    attributes:
      label: Disclosure Status
      description: Have you disclosed this vulnerability elsewhere?
      options:
        - "No - First disclosure"
        - "Yes - Disclosed to maintainers privately"
        - "Yes - Disclosed publicly"
        - "Yes - Disclosed to security researchers"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide details about the environment where this was discovered
      value: |
        - Version: [e.g., v1.2.3 or commit SHA]
        - Deployment: [e.g., local, staging, production]
        - OS: [e.g., Ubuntu 22.04]
        - Browser (if applicable): [e.g., Chrome 120]
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the security issue
      placeholder: |
        - Related security issues
        - Workarounds currently in place
        - Timeline considerations
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Security Reporting Checklist
      description: Please confirm the following
      options:
        - label: I have reviewed the security policy (SECURITY.md)
          required: true
        - label: This is not a critical vulnerability (or I have reported it privately)
          required: true
        - label: I have not included detailed exploit code in this public issue
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am willing to work with maintainers on responsible disclosure
          required: false
