# TTA Platform Feature Flags Configuration
# Phase 2A Integration - Multi-Stakeholder Web Interfaces & AI/ML Integration

# Global feature flags
global:
  # Core platform features
  therapeutic_gaming: true
  crisis_support: true
  accessibility_compliance: true
  data_privacy_protection: true
  
  # Phase 2A new features
  multi_stakeholder_interfaces: true
  ai_narrative_enhancement: true
  living_worlds_system: true
  real_time_clinical_monitoring: true
  
  # Advanced features (gradual rollout)
  advanced_therapeutic_gaming: false
  predictive_crisis_detection: false
  automated_intervention_triggers: false

# Patient Interface Features
patient_interface:
  # Core therapeutic features
  therapeutic_sessions: true
  progress_tracking: true
  emotional_state_monitoring: true
  crisis_support_button: true
  
  # Gaming and narrative features
  interactive_storytelling: true
  character_development: true
  choice_consequence_system: true
  adaptive_difficulty: true
  
  # AI-powered features
  ai_conversation_flow: true
  personalized_scenarios: true
  emotional_response_analysis: true
  intelligent_intervention_suggestions: true
  
  # Living worlds features
  dynamic_narrative_environments: true
  character_relationship_evolution: true
  persistent_world_state: true
  narrative_branching: true
  
  # Accessibility features
  screen_reader_support: true
  high_contrast_mode: true
  large_text_options: true
  keyboard_navigation: true
  voice_commands: false  # Future feature
  
  # Safety features
  automatic_crisis_detection: true
  emergency_contact_integration: true
  session_timeout_protection: true
  content_filtering: true

# Clinical Dashboard Features
clinical_dashboard:
  # Core monitoring features
  patient_overview: true
  real_time_alerts: true
  progress_visualization: true
  intervention_tracking: true
  
  # Advanced monitoring
  emotional_trend_analysis: true
  risk_assessment_dashboard: true
  multi_patient_monitoring: true
  alert_prioritization: true
  
  # AI-powered insights
  predictive_analytics: false  # Phase 3 feature
  automated_report_generation: true
  pattern_recognition: true
  intervention_effectiveness_analysis: true
  
  # Communication features
  secure_messaging: true
  video_consultation_integration: false  # Future feature
  appointment_scheduling: true
  emergency_escalation: true
  
  # Compliance features
  audit_logging: true
  hipaa_compliance_monitoring: true
  data_export_capabilities: true
  consent_management: true

# Developer Interface Features
developer_interface:
  # API documentation
  interactive_api_docs: true
  code_examples: true
  sdk_downloads: true
  testing_sandbox: true
  
  # Development tools
  api_key_management: true
  webhook_configuration: true
  rate_limit_monitoring: true
  error_tracking: true
  
  # Integration features
  third_party_integrations: true
  custom_therapeutic_frameworks: false  # Phase 3 feature
  plugin_system: false  # Future feature
  
  # Analytics
  usage_analytics: true
  performance_metrics: true
  integration_health_monitoring: true

# Admin Interface Features
admin_interface:
  # User management
  user_account_management: true
  role_based_access_control: true
  permission_management: true
  bulk_user_operations: true
  
  # System administration
  system_health_monitoring: true
  database_management: true
  backup_and_restore: true
  configuration_management: true
  
  # Security features
  security_audit_logs: true
  intrusion_detection: true
  data_encryption_management: true
  compliance_reporting: true
  
  # Feature flag management
  dynamic_feature_toggling: true
  a_b_testing_framework: true
  gradual_rollout_controls: true
  feature_usage_analytics: true

# AI and Machine Learning Features
ai_ml_features:
  # LangGraph integration
  conversation_flow_management: true
  therapeutic_intent_recognition: true
  context_aware_responses: true
  multi_turn_conversation_handling: true
  
  # Natural language processing
  sentiment_analysis: true
  emotion_detection: true
  crisis_keyword_detection: true
  therapeutic_language_optimization: true
  
  # Machine learning models
  personalization_engine: true
  adaptive_difficulty_adjustment: true
  intervention_recommendation: true
  outcome_prediction: false  # Phase 3 feature
  
  # Living worlds AI
  dynamic_character_behavior: true
  narrative_generation: true
  world_state_evolution: true
  player_choice_impact_modeling: true

# Database and Infrastructure Features
infrastructure:
  # Neo4j living worlds
  graph_database_integration: true
  relationship_modeling: true
  dynamic_world_updates: true
  narrative_persistence: true
  
  # Redis caching
  session_caching: true
  real_time_data_caching: true
  performance_optimization: true
  
  # PostgreSQL features
  advanced_querying: true
  data_analytics: true
  backup_automation: true
  
  # Microservices architecture
  service_discovery: true
  load_balancing: true
  circuit_breakers: true
  health_checks: true

# Security and Compliance Features
security:
  # Authentication and authorization
  multi_factor_authentication: true
  single_sign_on: false  # Future feature
  oauth2_integration: true
  jwt_token_management: true
  
  # Data protection
  end_to_end_encryption: true
  data_anonymization: true
  gdpr_compliance: true
  hipaa_compliance: true
  
  # Monitoring and auditing
  security_event_logging: true
  anomaly_detection: true
  penetration_testing_integration: false  # Future feature
  vulnerability_scanning: true

# Performance and Monitoring Features
monitoring:
  # Application performance
  real_time_metrics: true
  performance_profiling: true
  error_tracking: true
  uptime_monitoring: true
  
  # User experience monitoring
  page_load_analytics: true
  user_interaction_tracking: true
  accessibility_monitoring: true
  
  # Infrastructure monitoring
  resource_utilization_tracking: true
  database_performance_monitoring: true
  network_latency_monitoring: true
  
  # Alerting
  automated_alerting: true
  escalation_procedures: true
  incident_management: true

# Integration Features
integrations:
  # Healthcare systems
  ehr_integration: false  # Future feature
  fhir_compliance: false  # Future feature
  telehealth_platforms: false  # Future feature
  
  # Third-party services
  payment_processing: false  # Future feature
  calendar_integration: true
  email_notifications: true
  sms_notifications: true
  
  # Analytics platforms
  google_analytics: false  # Privacy considerations
  custom_analytics: true
  research_data_export: true

# Environment-specific overrides
environments:
  development:
    # Enable all features for development
    debug_mode: true
    verbose_logging: true
    test_data_generation: true
    mock_external_services: true
    
  staging:
    # Mirror production but with additional testing features
    load_testing: true
    performance_benchmarking: true
    security_testing: true
    
  production:
    # Conservative feature rollout
    advanced_therapeutic_gaming: false
    predictive_crisis_detection: false
    automated_intervention_triggers: false
    debug_mode: false
    verbose_logging: false

# A/B Testing Configuration
ab_testing:
  # Patient interface experiments
  narrative_style_variants: true
  ui_layout_experiments: true
  intervention_timing_tests: true
  
  # Clinical dashboard experiments
  alert_presentation_variants: true
  dashboard_layout_tests: true
  
  # AI model experiments
  conversation_model_variants: true
  intervention_algorithm_tests: true

# Gradual Rollout Configuration
rollout:
  # Percentage of users to receive new features
  ai_narrative_enhancement: 100  # Full rollout
  living_worlds_system: 100     # Full rollout
  real_time_clinical_monitoring: 100  # Full rollout
  advanced_therapeutic_gaming: 0      # Not yet enabled
  predictive_crisis_detection: 0     # Not yet enabled
  
  # Rollout strategy
  strategy: "percentage"  # Options: percentage, user_list, geographic
  
  # Rollback configuration
  automatic_rollback: true
  rollback_threshold: 5  # Percentage of errors that trigger rollback
  rollback_monitoring_window: 3600  # Seconds to monitor for issues
