carbon:
  enabled: true
  log_level: info
  measurement_interval: 15
  output_dir: logs/codecarbon
  project_name: TTA
  track_components: true
core_gameplay_loop:
  choice_architecture:
    consequence_preview: false
    enabled: true
    max_choices: 5
    min_choices: 2
    therapeutic_weighting: 0.4
  consequence_system:
    enabled: true
    learning_emphasis: true
    pattern_tracking: true
    therapeutic_framing: true
  enable_performance_tracking: true
  enabled: true
  max_concurrent_sessions: 100
  narrative_engine:
    complexity_adaptation: true
    enabled: true
    immersion_tracking: true
    max_description_length: 2000
    min_description_length: 100
  session_manager:
    auto_save_interval: 60
    context_preservation: true
    enabled: true
    therapeutic_goal_tracking: true
  session_timeout_minutes: 30
deeply:
  nested:
    new:
      key: 42
docker:
  compose_profiles:
  - default
  enabled: true
  ensure_consistent_env_vars: true
  ensure_consistent_extensions: true
  ensure_consistent_services: true
  standardize_container_names: true
  use_gpu: not_a_bool
environment:
  log_level: invalid_level
  name: development
level1:
  level2:
    level3: deep_value
model_management:
  default_provider: openrouter
  enabled: true
  fallback_config:
    enabled: true
    exclude_failed_models_minutes: 30
    fallback_strategy: performance_based
    max_retries: 3
    prefer_different_provider: true
  hardware_detection:
    cpu_core_threshold: 4
    enabled: true
    gpu_detection: true
    memory_threshold_gb: 4
  performance_monitoring:
    aggregation_interval_minutes: 5
    enabled: true
    metrics_retention_days: 30
    real_time_monitoring: true
  providers:
    custom_api:
      custom_providers:
        anthropic:
          api_key: ${ANTHROPIC_API_KEY}
          api_type: anthropic
          base_url: https://api.anthropic.com
          enabled: false
        openai:
          api_key: ${OPENAI_API_KEY}
          api_type: openai
          base_url: https://api.openai.com/v1
          enabled: false
      enabled: false
    lm_studio:
      base_url: http://localhost:1234
      enabled: false
    local:
      auto_quantization: true
      enabled: false
      gpu_memory_fraction: 0.8
      max_concurrent_models: 2
      models_cache_dir: ./models
      preferred_models:
      - microsoft/DialoGPT-medium
      - gpt2
    ollama:
      auto_pull_models: true
      base_url: http://localhost:11434
      docker_enabled: true
      docker_image: ollama/ollama:latest
      enabled: true
      gpu_enabled: true
      preferred_models:
      - llama3.1:8b
      - qwen2.5:7b
      - phi3:mini
    openrouter:
      api_key: ${OPENROUTER_API_KEY}
      base_url: https://openrouter.ai/api/v1
      cost_limit_per_request: 0.01
      enabled: true
      free_models_only: false
      preferred_models:
      - meta-llama/llama-3.1-8b-instruct:free
      - microsoft/phi-3-mini-128k-instruct:free
      - qwen/qwen-2-7b-instruct:free
  selection_strategy:
    algorithm: performance_based
    max_latency_ms: 5000
    prefer_free_models: true
    quality_threshold: 6.0
    therapeutic_safety_threshold: 7.0
  therapeutic_safety:
    content_filtering: true
    crisis_detection: true
    enabled: true
    minimum_safety_score: 7.0
new:
  section:
    key: value
new_key: new_value
new_setting: test_value
orchestration:
  components:
    agent_orchestration:
      class_name: AgentOrchestrationComponent
      path: src.components.agent_orchestration_component
    carbon:
      class_name: CarbonComponent
      path: src.components.carbon_component
    docker:
      class_name: DockerComponent
      path: src.components.docker_component
    gameplay_loop:
      class_name: GameplayLoopComponent
      path: src.components.gameplay_loop_component
    player_experience:
      class_name: PlayerExperienceComponent
      dependencies:
      - agent_orchestration
      path: src.components.player_experience_component
    tta_dev:
      class_name: TtaDevComponent
      path: ai-components.tta_dev.src.tta_dev_component
player_experience:
  api:
    cors_origins:
    - http://localhost:3000
    - https://localhost:3000
    host: 0.0.0.0
    port: 8080
  character_limits:
    character_name_max_length: 50
    max_characters_per_player: 5
  database:
    neo4j_password: password
    neo4j_url: bolt://localhost:7687
    neo4j_username: neo4j
    redis_url: redis://localhost:6379
  enabled: true
  security:
    jwt_algorithm: HS256
    jwt_expire_minutes: 30
    jwt_secret_key: your-secret-key-change-in-production
  therapeutic:
    crisis_detection_enabled: true
    default_intensity: medium
    safety_monitoring_interval: 300
  web:
    build_path: build
    port: 3000
  world_management:
    compatibility_threshold: 0.6
    world_cache_ttl: 86400
test:
  key: updated
test_save_key: test_save_value
test_save_key_json: test_save_value_json
tta:
  dev:
    components:
      llm:
        api_base: http://test:1234/v1
        model: test-model
      neo4j:
        port: 7688
tta.dev:
  components:
    llm:
      api_base: http://localhost:1234/v1
      enabled: true
      model: qwen2.5-7b-instruct
    neo4j:
      enabled: true
      password: password
      port: 7687
      username: neo4j
  enabled: false
tta.prototype:
  components:
    app:
      enabled: true
      port: 8501
    narrative_arc_orchestrator:
      enabled: true
    neo4j:
      enabled: true
      password: password
      port: 7688
      username: neo4j
  enabled: true
tta.staging:
  components:
    app:
      enabled: true
      port: 8502
    narrative_arc_orchestrator:
      emergent_generation:
        complexity_limit: 5
        probability_threshold: 0.7
      enabled: true
      max_concurrent_sessions: 100
      narrative_scales:
        epic_term_window: 31536000
        long_term_window: 2592000
        medium_term_window: 86400
        short_term_window: 300
      port: 8502
      therapeutic_integration:
        safety_check_interval: 60
        therapeutic_weight: 0.3
    neo4j:
      database: tta-staging
      enabled: true
      memory:
        heap_initial: 1G
        heap_max: 4G
        pagecache: 2G
      password: staging_password_change_me
      port: 7689
      username: neo4j
  enabled: true
