# Hot reloading overrides for TTA development
# Usage: docker-compose -f tta.dev/docker-compose.yml -f docker-compose.hotreload.yml up

version: '3.8'

services:
  # Hot reloading configurations for all TTA services
  admin-api:
    build:
      target: builder  # Use builder stage with development dependencies
    volumes:
      - ./src:/app/src:cached
      - ./tests:/app/tests:cached
      - ./pyproject.toml:/app/pyproject.toml:cached
      - ./uv.lock:/app/uv.lock:cached
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app/src
      - RELOAD=true
    command: ["uv", "run", "uvicorn", "src.admin_api.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload", "--reload-dir", "/app/src"]

  clinical-api:
    build:
      target: builder
    volumes:
      - ./src:/app/src:cached
      - ./tests:/app/tests:cached
      - ./pyproject.toml:/app/pyproject.toml:cached
      - ./uv.lock:/app/uv.lock:cached
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app/src
      - RELOAD=true
    command: ["uv", "run", "uvicorn", "src.clinical_api.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload", "--reload-dir", "/app/src"]

  developer-api:
    build:
      target: builder
    volumes:
      - ./src:/app/src:cached
      - ./tests:/app/tests:cached
      - ./pyproject.toml:/app/pyproject.toml:cached
      - ./uv.lock:/app/uv.lock:cached
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app/src
      - RELOAD=true
    command: ["uv", "run", "uvicorn", "src.developer_api.main:app", "--host", "0.0.0.0", "--port", "8003", "--reload", "--reload-dir", "/app/src"]

  patient-api:
    build:
      target: builder
    volumes:
      - ./src:/app/src:cached
      - ./tests:/app/tests:cached
      - ./pyproject.toml:/app/pyproject.toml:cached
      - ./uv.lock:/app/uv.lock:cached
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app/src
      - RELOAD=true
    command: ["uv", "run", "uvicorn", "src.patient_api.main:app", "--host", "0.0.0.0", "--port", "8004", "--reload", "--reload-dir", "/app/src"]

  langgraph:
    build:
      target: builder
    volumes:
      - ./src:/app/src:cached
      - ./tests:/app/tests:cached
      - ./pyproject.toml:/app/pyproject.toml:cached
      - ./uv.lock:/app/uv.lock:cached
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app/src
      - RELOAD=true
      - TOKENIZERS_PARALLELISM=false
    command: ["uv", "run", "uvicorn", "src.langgraph_service.main:app", "--host", "0.0.0.0", "--port", "8005", "--reload", "--reload-dir", "/app/src"]
