# GitHub Pages Configuration for TTA Documentation
# This file configures Jekyll for rendering the documentation site

# Site settings
title: TTA Documentation
description: >-
  Therapeutic Text Adventure Platform - Comprehensive documentation for developers,
  clinical staff, and users. AI-powered interactive storytelling with evidence-based
  therapeutic techniques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theinterneti.github.io/TTA" # the base hostname & protocol for your site

# Theme
theme: jekyll-theme-cayman
# Alternative themes available on GitHub Pages:
# - jekyll-theme-minimal
# - jekyll-theme-slate
# - jekyll-theme-architect
# - jekyll-theme-dinky
# - jekyll-theme-hacker
# - jekyll-theme-leap-day
# - jekyll-theme-merlot
# - jekyll-theme-midnight
# - jekyll-theme-modernist
# - jekyll-theme-tactile
# - jekyll-theme-time-machine

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links

# Relative links configuration
relative_links:
  enabled: true
  collections: false

# Include/Exclude files
include:
  - README.md
  - DOCUMENTATION_INDEX.md
  - index.md
  - _config.yml

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - "*.sh"
  - "*.py"

# Collections (if needed in the future)
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Navigation (can be used by themes)
navigation:
  - title: Home
    url: /
  - title: Documentation Index
    url: /DOCUMENTATION_INDEX.html
  - title: Getting Started
    url: /setup/DEVELOPMENT_SETUP.html
  - title: Architecture
    url: /Documentation/architecture/README.html
  - title: Testing
    url: /testing/TESTING_GUIDE.html
  - title: Deployment
    url: /deployment/PRODUCTION_DEPLOYMENT_GUIDE.html
  - title: Security
    url: /SECURITY.html
  - title: Contributing
    url: /CONTRIBUTING.html

# SEO settings
author: TTA Development Team
twitter:
  username: # Add if available
  card: summary_large_image

# Social links
github_username: theinterneti
repository: theinterneti/TTA

# Google Analytics (add if needed)
# google_analytics: UA-XXXXXXXX-X

# Additional metadata
lang: en-US
timezone: UTC

# Markdown extensions
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

