# TTA Test Environment Override
# Usage: docker-compose -f docker/compose/docker-compose.base.yml -f docker/compose/docker-compose.test.yml up

services:
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # Neo4j - Test Configuration (Constrained for CI)
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  neo4j:
    environment:
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=256m
      - NEO4J_dbms_logs_debug_level=WARN
    volumes:
      - tta_neo4j_test_data:/data
    secrets:
      - neo4j_auth
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 512M

  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # Redis - Test Configuration
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  redis:
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --requirepass ${REDIS_PASSWORD:-test_redis_password}
    volumes:
      - tta_redis_test_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # Prometheus - Test Configuration (Minimal)
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  prometheus:
    volumes:
      - ../../monitoring/prometheus/prometheus.test.yml:/etc/prometheus/prometheus.yml:ro
      - tta_prometheus_test_data:/prometheus

  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # Grafana - Not included in test environment (too heavy for CI)
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # grafana:
  #   profiles:
  #     - full-test  # Only start with: --profile full-test

volumes:
  tta_neo4j_test_data:
  tta_redis_test_data:
  tta_prometheus_test_data:

secrets:
  neo4j_auth:
    file: ../../secrets/test/neo4j_auth.txt
