name: Auto-Merge to Development

on:
  pull_request:
    branches:
      - development
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Enable Auto-Merge
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.draft == false &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    
    steps:
      - name: Enable auto-merge for PR
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Auto-merge enabled** for this PR targeting `development` branch.\n\nThis PR will be automatically merged when all required status checks pass:\n- ✅ Unit tests\n\n*Note: Auto-merge will be cancelled if any check fails.*'
            })

  check-status:
    name: Monitor Status Checks
    runs-on: ubuntu-latest
    needs: auto-merge
    if: always()
    
    steps:
      - name: Wait for status checks
        run: |
          echo "Monitoring status checks for auto-merge..."
          echo "PR will auto-merge when all checks pass."
      
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Auto-merge failed** - Unit tests did not pass.\n\nPlease review the failed checks and push fixes to enable auto-merge again.'
            })

