name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'Documentation/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation Site
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git info
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create documentation site structure
        run: |
          mkdir -p _site
          
          # Copy main documentation
          cp -r docs/* _site/
          
          # Copy additional documentation
          mkdir -p _site/Documentation
          cp -r Documentation/* _site/Documentation/
          
          # Copy root documentation files
          cp README.md _site/
          cp CHANGELOG.md _site/ || echo "CHANGELOG.md not found yet"
          cp CONTRIBUTING.md _site/ || echo "CONTRIBUTING.md not found"
          cp SECURITY.md _site/ || echo "SECURITY.md not found"
          
          # Create index.html that redirects to docs/README.md
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta http-equiv="refresh" content="0; url=./README.html">
              <title>TTA Documentation</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                      margin: 0;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                  }
                  .container {
                      text-align: center;
                      padding: 2rem;
                  }
                  h1 {
                      font-size: 2.5rem;
                      margin-bottom: 1rem;
                  }
                  p {
                      font-size: 1.2rem;
                      margin-bottom: 2rem;
                  }
                  a {
                      color: white;
                      text-decoration: none;
                      padding: 1rem 2rem;
                      background: rgba(255, 255, 255, 0.2);
                      border-radius: 8px;
                      transition: background 0.3s;
                  }
                  a:hover {
                      background: rgba(255, 255, 255, 0.3);
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🎭 TTA Documentation</h1>
                  <p>Therapeutic Text Adventure Platform</p>
                  <p>Redirecting to documentation...</p>
                  <a href="./README.html">View Documentation</a>
              </div>
          </body>
          </html>
          EOF
          
          # Create a simple CSS file for better markdown rendering
          cat > _site/style.css << 'EOF'
          body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
              line-height: 1.6;
              max-width: 1200px;
              margin: 0 auto;
              padding: 2rem;
              color: #333;
          }
          
          h1, h2, h3, h4, h5, h6 {
              margin-top: 1.5rem;
              margin-bottom: 1rem;
              font-weight: 600;
          }
          
          h1 { font-size: 2.5rem; border-bottom: 2px solid #667eea; padding-bottom: 0.5rem; }
          h2 { font-size: 2rem; border-bottom: 1px solid #e0e0e0; padding-bottom: 0.3rem; }
          h3 { font-size: 1.5rem; }
          
          code {
              background: #f5f5f5;
              padding: 0.2rem 0.4rem;
              border-radius: 3px;
              font-family: 'Courier New', monospace;
          }
          
          pre {
              background: #f5f5f5;
              padding: 1rem;
              border-radius: 5px;
              overflow-x: auto;
          }
          
          pre code {
              background: none;
              padding: 0;
          }
          
          a {
              color: #667eea;
              text-decoration: none;
          }
          
          a:hover {
              text-decoration: underline;
          }
          
          table {
              border-collapse: collapse;
              width: 100%;
              margin: 1rem 0;
          }
          
          th, td {
              border: 1px solid #ddd;
              padding: 0.75rem;
              text-align: left;
          }
          
          th {
              background: #667eea;
              color: white;
          }
          
          tr:nth-child(even) {
              background: #f9f9f9;
          }
          
          blockquote {
              border-left: 4px solid #667eea;
              padding-left: 1rem;
              margin-left: 0;
              color: #666;
          }
          
          img {
              max-width: 100%;
              height: auto;
          }
          
          .badge {
              display: inline-block;
              padding: 0.25rem 0.5rem;
              border-radius: 3px;
              font-size: 0.875rem;
              font-weight: 600;
          }
          EOF
      
      - name: Convert Markdown to HTML (using GitHub's markdown API)
        run: |
          # This step would ideally use a markdown processor
          # For now, GitHub Pages will render markdown files directly
          echo "Markdown files will be rendered by GitHub Pages"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
  
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Output deployment URL
        run: |
          echo "Documentation deployed to: ${{ steps.deployment.outputs.page_url }}"
          echo "Main documentation: ${{ steps.deployment.outputs.page_url }}README.html"
          echo "Documentation index: ${{ steps.deployment.outputs.page_url }}DOCUMENTATION_INDEX.html"

